### ISSUE TITLE
run app

### ISSUE THREAD

**Issue by alfredogama** [felangel/flutter_hub#6]
Hello,
I'd like to test your example but I got this error message: 
Because flutter_hub depends on flutter_bloc >=0.1.1 <7.0.0-nullsafety.0 which doesn't support null safety,
  version solving failed.

how can I update the code to run your demo?

**Comment by raheelism** [comment]
you can use the following command to run the application.

`flutter run --no-sound-null-safety`

This error is due to null safety. As the version doesnt support null safety.

**Comment by felangel** [comment]
This project is quite old and isn't maintained so you'd need to either run it with no sound null safety using an older version of Flutter or upgrade it to the latest stable version.
